name: guardowl
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.4
  http: ^1.2.2
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/guardowl_.png
    - assets/logos/guardowl_.svg
    - assets/logos/logo_guardowl.png
    - assets/icons/appbar/menu.png
    #logos social network
    - assets/icons/authentication/